/**
 * © 2024 DivineDemonGaming Inc. All Rights Reserved.
 * Owner: DivineDemonGaming Inc. | Product: VENTURE Creator Platform
 */

export const LEGAL_VERSIONS = {
  terms: '1.0',
  privacy: '1.0',
  kidsTerms: '1.0',
};

export const AGE_GROUPS = {
  KIDS: 'KIDS',     // Under 13 — VENTURE Kids mode, parent-managed
  TEEN: 'TEEN',     // 13–17 — restricted experience
  ADULT: 'ADULT',   // 18+ — full access
};

export const MIN_ACCOUNT_AGE = 13;
export const TEEN_MAX_AGE = 17;
export const KIDS_MAX_AGE = 12;

export function getAgeGroup(birthYear, birthMonth, birthDay) {
  const today = new Date();
  const birth = new Date(birthYear, birthMonth - 1, birthDay);
  let age = today.getFullYear() - birth.getFullYear();
  const m = today.getMonth() - birth.getMonth();
  if (m < 0 || (m === 0 && today.getDate() < birth.getDate())) age--;
  if (age <= KIDS_MAX_AGE) return AGE_GROUPS.KIDS;
  if (age <= TEEN_MAX_AGE) return AGE_GROUPS.TEEN;
  return AGE_GROUPS.ADULT;
}

export const KIDS_CONTENT_CATEGORIES = {
  EDUCATIONAL: 'Educational',
  ANIMATION: 'Animation',
  MUSIC: 'Music',
  ARTS_CRAFTS: 'Arts & Crafts',
  SCIENCE: 'Science',
  STORIES: 'Stories',
  NATURE: 'Nature',
  SPORTS: 'Sports',
  GAMING_FAMILY: 'Family Gaming',
};

export const KIDS_TIME_LIMITS = [
  { label: 'No Limit', value: 0 },
  { label: '30 minutes', value: 30 },
  { label: '1 hour', value: 60 },
  { label: '1.5 hours', value: 90 },
  { label: '2 hours', value: 120 },
  { label: '3 hours', value: 180 },
];

export const TERMS_OF_SERVICE = `VENTURE CREATOR PLATFORM — TERMS OF SERVICE

Last updated: 2024 | Version 1.0
© 2024 DivineDemonGaming Inc. All Rights Reserved.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. ACCEPTANCE OF TERMS

By accessing or using VENTURE ("the Platform"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Platform.

VENTURE is operated by DivineDemonGaming Inc. ("we," "us," or "our"). These Terms govern your use of our mobile application, web studio, and all related services.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

2. ELIGIBILITY & AGE REQUIREMENTS

Users 13 and older may create accounts on VENTURE. Users between 13 and 17 years old ("Teens") may use the Platform with certain restrictions applied automatically.

Children under 13 may use VENTURE Kids — a separate, parent-managed experience — only with verified parental consent in compliance with COPPA (Children's Online Privacy Protection Act).

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

3. ACCOUNTS

You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

4. CONTENT STANDARDS

Users may not post content that is illegal, harmful, threatening, abusive, defamatory, or violates any third-party rights. We reserve the right to remove content that violates these standards.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

5. INTELLECTUAL PROPERTY

Content you post on VENTURE remains your property. By posting, you grant DivineDemonGaming Inc. a non-exclusive license to display, distribute, and promote your content on the Platform.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

6. PRIVACY

Your use of the Platform is subject to our Privacy Policy, incorporated herein by reference.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

7. TERMINATION

We reserve the right to suspend or terminate accounts that violate these Terms.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

8. LIMITATION OF LIABILITY

To the maximum extent permitted by law, DivineDemonGaming Inc. shall not be liable for any indirect, incidental, or consequential damages.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

9. GOVERNING LAW

These Terms are governed by the laws of the United States.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

10. CONTACT

Questions about these Terms? Email: legal@divinedemongaming.com`;

export const PRIVACY_POLICY = `VENTURE CREATOR PLATFORM — PRIVACY POLICY

Last updated: 2024 | Version 1.0
© 2024 DivineDemonGaming Inc. All Rights Reserved.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. INFORMATION WE COLLECT

We collect information you provide directly (account registration, profile, content uploads), information generated by your use of the Platform (activity logs, device identifiers), and information from third parties (OAuth sign-in providers).

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

2. HOW WE USE YOUR INFORMATION

We use your information to provide and improve the Platform, personalize your experience, send notifications, enforce our policies, and comply with legal obligations.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

3. CHILDREN'S PRIVACY (COPPA)

VENTURE Kids is available for children under 13 only with verifiable parental consent. We collect minimal data for children: only a display name and avatar. We do not serve targeted advertising to children. Parents may review, modify, or delete their child's data at any time by contacting privacy@divinedemongaming.com.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

4. DATA SHARING

We do not sell your personal information. We may share data with service providers who assist in operating the Platform, and when required by law.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

5. DATA RETENTION

We retain your data for as long as your account is active or as needed to provide services.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

6. YOUR RIGHTS

You may access, correct, or delete your personal data. Contact privacy@divinedemongaming.com.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

7. CONTACT

Privacy inquiries: privacy@divinedemongaming.com`;

export const TEEN_SAFETY_NOTICE = `VENTURE — TEEN SAFETY NOTICE

As a user between 13 and 17 years old, your VENTURE experience includes these protections:

• Direct messages are restricted to mutual followers only
• Your account is private by default
• Location data is never shared or displayed
• Monetization features require age verification
• Sensitive content is filtered automatically
• We do not serve targeted advertising based on your activity
• You can report content or users at any time using the flag icon

Your safety is our priority. If you experience harassment or inappropriate content, please report it immediately.

Contact our Safety Team: safety@divinedemongaming.com`;

export const KIDS_PARENTAL_CONSENT = `VENTURE KIDS — PARENTAL CONSENT & TERMS

Last updated: 2024 | Version 1.0
© 2024 DivineDemonGaming Inc. All Rights Reserved.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ABOUT VENTURE KIDS

VENTURE Kids is a safe, curated experience for children under 13. It is separate from the main VENTURE platform and designed specifically for young audiences.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

AS A PARENT/GUARDIAN, YOU CONFIRM THAT:

• You are at least 18 years of age
• You are the parent or legal guardian of the child using this account
• You consent to your child using VENTURE Kids under the terms below
• You will supervise your child's use of the Platform

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

WHAT VENTURE KIDS INCLUDES:

✓ Curated, age-appropriate content only
✓ No direct messaging or live chat
✓ No comments visible to your child
✓ No advertising
✓ No monetization features
✓ Parental time limits and content category controls
✓ PIN-protected exit from Kids Mode
✓ Content reviewed and approved for kids audiences

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DATA WE COLLECT FOR YOUR CHILD:

• Display name (you set this)
• Avatar selection
• Viewing activity (used only to improve recommendations)

We do NOT collect your child's email, phone number, or real name. We do NOT serve advertising to children. We do NOT share your child's data with third parties.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

YOUR PARENTAL RIGHTS:

• Review your child's viewing history at any time
• Modify or delete your child's profile
• Remove parental consent and delete all data by contacting privacy@divinedemongaming.com
• Change parental controls at any time using your PIN

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

COMPLIANCE

VENTURE Kids is operated in compliance with the Children's Online Privacy Protection Act (COPPA), 15 U.S.C. §§ 6501–6506, and the FTC's COPPA Rule, 16 C.F.R. Part 312.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CONTACT

Questions or data requests: privacy@divinedemongaming.com
Kids Safety Team: safety@divinedemongaming.com`;
